@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.gizmo.doiamengineering.util;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;