@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.gizmo.doiamengineering.entity;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;